apiVersion: v1
kind: Service
metadata:
  name: digital-twin-service
spec:
  type: NodePort
  selector:
    app: digital-twin-health
  ports:
    - port: 1880
      targetPort: 1880
      nodePort: 30007
